### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by kakaluote444** [lerman01/SpotlightDownloader#1]
java.lang.Exception: Error while fetching image data (response: null)
	at spotlightextractor.Worker.fetchImageData(Worker.java:140) ~[classes/:?]
	at spotlightextractor.Worker.fetchData(Worker.java:78) [classes/:?]
	at spotlightextractor.Worker.run(Worker.java:73) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by lerman01** [comment]
@kakaluote444 do you still have this problem ?

**Comment by lerman01** [comment]
Issue not reproduced
